[settings]
active_indexers = ["pangea"]

[websockets]
envio_url = "ws://localhost:8080/v1/graphql"
subsquid_url = "ws://localhost:4001/graphql"
pangea_username =  "username"
pangea_pass = "pass"

[contract]
contract_id = "0x598181fdf206ef2109967be6c4ad75c338a1f082f27d98fedeacd5591c34552c"
contract_block = 10000000
order_limit = 10

[matchers]
matchers = ["20faf0f7-94a9-4651-a073-9f4d376201fa","fbf16c35-a12e-4eda-87f3-be18dc91d6cd","38647325-de9c-47ff-85cf-39231abed68c"]
matcher_ws_port = 9001
batch_size = 25

[server]
server_port = 9090
