replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: spark-middleware.production.sprk.fi
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: spark-middleware-tls
      hosts:
        - spark-middleware.production.sprk.fi

vault:
  mount: production
